### ISSUE TITLE
Could not extract information

### ISSUE THREAD

**Issue by paulose** [BlinkID/blinkid-in-browser#10]
I have taken the JS example and tried to run it on a Philippines Driver License card. The example says "Could not extract information". The same example provided on your CodePen links provide the same message. Am I missing something?

![image](https://user-images.githubusercontent.com/112645/93414527-1dc34580-f8bf-11ea-94f0-553c029c3548.png)

**Comment by eddieMicroblink** [comment]
Hi @paulose 

Have you tried using the [demo app](https://demo.microblink.com/in-browser-sdk/blinkid/index.html#)?
Also, please make sure the edges of the document are visible on the image. It would be optimal if the document took up around 70% of the image.

**Comment by paulose** [comment]
@eddieMicroblink  I just tried that and it gets stuck at 

![image](https://user-images.githubusercontent.com/112645/93468710-04e18100-f90d-11ea-9d8b-0e2c6ed3409f.png)

The image I am trying to upload has the ID card at almost 100% of the image. There is no other background.

**Comment by eddieMicroblink** [comment]
@paulose in that case please try adding a contrasting margin around the document, making the edges of the document more pronounced should help with document detection

**Comment by paulose** [comment]
@eddieMicroblink  The same image works well on this demo endpoint https://microblink.com/products/blinkid/web-api

**Comment by vjekoart** [comment]
This behaviour is most probably caused by limited computing power on mobile and desktop devices.

It's possible to get an unsuccessful scan when option _From gallery_ is used, while scanning the same image with camera from mobile device results with successful scan. That is, when option _Device camera_ is used and the image is displayed on another display.

The reason for this is the way the SDK operates. When option _From gallery_ is used, all data must be extracted from a single frame. Which is not always possible due to limited computing power. On the other hand, when an image is scanned with the camera, multiple frames are processed, so all relevant data can be extracted in a couple of iterations.
