### ISSUE TITLE
Not able to scan the documents using webcam

### ISSUE THREAD

**Issue by pjain8889** [BlinkID/blinkid-in-browser#12]
I am not able to scan the documents like Aadhar Card, PAN Card using the below demo links:

https://codepen.io/microblink/pen/BajeeMx
https://demo.microblink.com/in-browser-sdk/blinkid/index.html

I am using webcam (logitech HD 720p) to scan the documents.

I am not sure what I missing here. Can anyone help me here.

Thanks in Advance !!!

**Comment by vjekoart** [comment]
Hello @pjain8889,

We need more information to identify the problem.

1. What is the exact information you get when scanning?
2. Have you tried scanning from the image instead of webcam for these documents?
3. Are you scanning sample documents or the real ones?

It would be helpful if you could share document images with us so we can reproduce the problem. You can use _Secure upload_ functionality on our [Developer Dashboard](https://microblink.com/customer/secure-upload) to send images in a safe way.

Sincerely,
Vjekoslav

**Comment by vjekoart** [comment]
Hi @pjain8889,

Have you managed to solve aforementioned problem?

If not, I would advise you to contact our support at [help.microblink.com](http://help.microblink.com/) to get further information.
