### ISSUE TITLE
'@PLACEHOLDER:worker' leads to Uncaught SyntaxError: Invalid or unexpected token

### ISSUE THREAD

**Issue by sveres** [BlinkID/blinkid-in-browser#20]
https://github.com/BlinkID/blinkid-in-browser/blob/d957f538c0dc76caf30d5aeed4408d95e2b5b428/src/MicroblinkSDK/MicroblinkSDK.ts#L134

Hey guys, just tried the new version of the sdk, and after upgrading the resources I run into this issue.
if I try to run the demo app, e.g. blinkid-camera, everything works fine, in that case the linked line has the real minified worker hardcoded.

Is this intended and I am the one who is doing something wrong or is this a bug?

**Comment by vjekoart** [comment]
Hi @sveres,

Placeholder string is intentionally placed in the `src/MicroblinkSDK/MicroblinkSDK.ts` file. If you check the [rollup.config.js](https://github.com/BlinkID/blinkid-in-browser/blob/master/rollup.config.js) file, there is a logic which will replace placeholder string with actual worker content during the build action.

We've decided to use this approach so we can simplify usage of the SDK. In the latest version there is no property `WasmLoadSettings.workerLocation` since the worker is inlined. This should simplify deployment procedure, since there is no need to host the worker file.

If worker source files are modified and action `npm run build` is executed, the output in `{dist,es,lib}` directories will include the latest worker file.

Hope this helps.

Sincerely,
Vjekoslav

**Comment by sveres** [comment]
Hi Vjekoslav,

Yes this clarifies a lot, thank you.
