### ISSUE TITLE
Upload file not working

### ISSUE THREAD

**Issue by SpajicM** [BlinkID/blinkid-in-browser#24]
Hi,

when I scan the document through camera, it works, but if I try to upload it via file upload (high quality scanned image) I get:
**_unable to read the document. Please try again._**

I've tried on Windows' Chrome and Firefox, and on Mac's Chrome.

**Comment by vjekoart** [comment]
Hi @SpajicM,

We're aware of the problem when the document is unsuccessfully scanned from an image file.

The reason for this is the way the SDK operates. When scanning from an image file, all data must be extracted from a single frame. Which is not always possible due to limited computing power. On the other hand, when an image is scanned with the camera, multiple frames are processed, so all relevant data can be extracted in a couple of iterations.

We're working on a solution for this problem, but we're not sure when the update will be released. We'll make sure to highlight the improvement in [CHANGELOG.md](https://github.com/BlinkID/blinkid-in-browser/blob/master/CHANGELOG.md) file when development is finished.

Sincerely,
Vjekoslav

**Comment by SpajicM** [comment]
Hi,

thank you for clarification.
It might be a good idea to put a note about it in README for time being.

**Comment by vjekoart** [comment]
Hi @SpajicM,

Thanks for the suggestion, it sounds helpful. We're going to add a note to README.

**Comment by vjekoart** [comment]
We're currently developing a solution for this problem.

When the relevant version of the SDK will be published, it will be referenced in this issue.

**Comment by vjekoart** [comment]
Hi @SpajicM,

The latest version of BlinkID In-browser SDK comes with a new feature that adds support to scan cropped images when using file upload.

More information about the feature can be found under [this section](https://github.com/BlinkID/blinkid-in-browser/blob/master/CHANGELOG.md#changes-to-the-blinkidcombinedrecognizer) in the release notes. Check out the last point.

I'm assuming that you've tried to upload a cropped document image. Let me know if that was not the case.

Sincerely,
Vjekoslav
