### ISSUE TITLE
Camera Selection 

### ISSUE THREAD

**Issue by Hazem-Musallam** [BlinkID/blinkid-in-browser#29]
Hi , 
i used the sample that in the  web sdk menu but i faced an issue , 
in the browser the opened camera is the front one , 
but when i run the same code on mobile browser the opened on is the rear camera , 
there is no selection to which one to use.

**Comment by vjekoart** [comment]
Hi @Hazem-Musallam,

This is due to default camera selection mechanism in the SDK. We don't have a UI for camera selection.

However, in the release 5.9.0 we've added a method to the SDK and property to UI component which can be used to preselect a camera device based on the camera ID.

You can read the relevant part of the release notes [here](https://github.com/BlinkID/blinkid-in-browser/blob/master/CHANGELOG.md#camera-management-updates).

Information in release notes also has links to relevant source code files.

Sincerely,
Vjekoslav
