### ISSUE TITLE
is it possible to crop a face from a document with a Combined Recognizer?

### ISSUE THREAD

**Issue by victory-sokolov** [BlinkID/blinkid-in-browser#30]
Greetings,

I'm looking for a way to detect a face in the document and draw a quad around the face and crop the face from the document.
Particularly interested in the implementation in `CombinedRecognizer`.
Didn't find any settings related to face in `BlinkIdCombinedRecognizerResult`.

**Comment by vjekoart** [comment]
Hi @victory-sokolov,

It's not possible to detect the face and draw a quad during the scan action, regardless of the recognizer which is used.

However, it's possible to get the face image in the result of both `BlinkIdRecognizer` and `BlinkIdCombinedRecognizer`.

To achieve that, it's required to set the `returnFaceImage` recognizer option. Setting a recognizer option is different for the UI component and WASM library.

If the UI component is used, it's possible to set an option in the following manner:

```html
<blinkid-in-browser ... recognizer="BlinkIdCombinedRecognizer" recognizer-options="returnFaceImage"></blinkid-in-browser>
```

If the WASM library is used, setting a recognizer option is a bit more complicated:

```typescript
...

// Create new instance of recognizer
const recognizer = await BlinkIDSDK.createBlinkIdCombinedRecognizer( sdk );

// Update recognizer settings before scan action
const settings = await recognizer.currentSettings();

settings[ "returnFaceImage" ] = true;

await recognizer.updateSettings( settings );

...
```

Hope this helps!

Sincerely,
Vjekoslav

**Comment by victory-sokolov** [comment]
Greetings!

Sorry once again for the same question, but I cannot find a way to get face image in `ImageCaptureRecognizer`, 
seems like there are only two options that can be updated or maybe I'm missing something?

I'm interested particularly in face image in Base64 encoding or just an ImageData.

**Comment by vjekoart** [comment]
Hi @victory-sokolov,

If you're talking about [`BlinkIdImageCaptureRecognizer`](https://github.com/BlinkID/blinkid-imagecapture-in-browser/blob/main/src/Recognizers/BlinkID/ImageCapture/ImageCaptureRecognizer.ts), it's part of the [BlinkID ImageCapture In-Browser SDK](https://github.com/BlinkID/blinkid-imagecapture-in-browser) product.

That recognizer is quite different from `BlinkIDRecognizer` and `BlinkIDCombinedRecognizer` since the purpose of ImageCapture SDK is different than this one.

If you're using BlinkID ImageCapture In-browser SDK, I would advise you to open an issue in that repository :)

In any case, `BlinkIdImageCaptureRecognizer` does not support extraction of face images. But rather it's intended to be used in combination with [BlinkID Cloud API](https://microblink.com/products/blinkid/cloud-api) or [BlinkID Self-hosted API](https://microblink.com/products/blinkid/self-hosted-api) solutions. In this scenario, recognition and extraction of face images are executed on the backend.

Sincerely,
Vjekoslav

**Comment by victory-sokolov** [comment]
Ok, thank you!
Already find out an option to get it on the backend
