### ISSUE TITLE
Not able to find a way to provide license file instead of string

### ISSUE THREAD

**Issue by zohaibarshad-ai** [BlinkID/blinkid-in-browser#39]
In blink id In-browser SDK I am trying to provide my license file instead of a string and cannot a find a way to do it. 

I looked into blink id android sdk and there is a function "setLicenseFile" through which we can provide license file instead of a string. It will be great if similar type of feature is available in blink id In-browser SDK . 

Thanks.

**Comment by vjekoart** [comment]
Hi @zohaibarshad-ai,

There is no way of setting a license key with a license file.

This feature is not on a roadmap since there wouldn't be any differences from a security standpoint if one would load a license from a file. Also, the user experience would be slightly worse since a web app would need to make an additional network request resulting in a longer initialization time.

Sincerely,
Vjekoslav

**Comment by zohaibarshad-ai** [comment]
Thanks @vjekoart,
