### ISSUE TITLE
Yarn install results in: " Invalid hosted git fragment..."

### ISSUE THREAD

**Issue by sveres** [BlinkID/blinkid-in-browser#5]
If I try to add the sdk with yarn add or adding it manually and then running yarn install, I get:
Invalid hosted git fragment "github:BlinkID:blinkid-in-browser".

Installing it with npm works fine.

Yarn v1.22.0
Node v10.16.0

**Comment by vjekoart** [comment]
Hi @sveres,

Thank you for the feedback. It looks like we have a typo in `package.json`. Instead of `"repository": "github:BlinkID/blinkid-in-browser",` we have `"repository": "github:BlinkID:blinkid-in-browser",`.

We're going to publish a fix as soon as possible. In the meantime, it's recommended to use `npm --save @microblink/blinkid-in-browser-sdk` for installation of package.

Furthermore, I'd like to point out that we've developed this package with Node v12.x. With the upcoming release, we're going to specify that version inside the `package.json`.

**Comment by vjekoart** [comment]
Issue has been fixed with release v5.5.1.
