### ISSUE TITLE
WORKER_RUNNER_CREATION_FAILURE on Android 12 / Samsung / Chrome 96

### ISSUE THREAD

**Issue by tzusman** [BlinkID/blinkid-in-browser#76]
Hi there,

Our integration is working great across many browsers, but this Samsung device in Chrome is failing to initialize the runner.  In the Samsung browser on the same device, there's no issue.  Any ideas on how to debug this issue, or if you've seen it before?

Thanks! 

![Screen Shot 2022-06-07 at 10 26 42 AM](https://user-images.githubusercontent.com/113902/172434023-2bf01a40-9886-49e9-9b59-3c403f6a08fa.png)

**Comment by AngTim** [comment]
Hello Todd,

I hope you're doing well and staying safe.
Thank you for sending a screenshot of your error.
It seems like the issue is related to the dedicated memory in your environment; as a first suggestion, It would be best first to update your chrome browser and check if there are visible differences or if the issue persists.
Also, the mobile device's technical specifications could affect the process and cause the said issue.

WORKER_RUNNER_CREATION_FAILURE`: there is enough memory to load WebAssembly, but there isn't enough memory to create a recognizer runner to start the recognition process.

If you have any additional information or questions, feel free to contact us.

Kind regards,
Angelo
Web Support Associate

**Comment by AngTim** [comment]
There were no further updates regarding the issue after the first follow-up.
