### ISSUE TITLE
Getting Error of Loading worker while intialize

### ISSUE THREAD

**Issue by pjain8889** [BlinkID/blinkid-in-browser#9]
I am trying to setup Microblink Browser SDK in my angular project by referring the below link but I am getting the error during the initialization of the worker.
Refer link: https://github.com/BlinkID/blinkid-in-browser

Error Screenshot:
![Config3](https://user-images.githubusercontent.com/67706842/93075299-39ea9b00-f6a3-11ea-937e-8343f20a1c3a.png)

Firstly, I run the command "npm install @microblink/blinkid-in-browser-sdk" in the project and then import it in the component.
I am using the below code to run:

import * as BlinkIDSDK from "@microblink/blinkid-in-browser-sdk";

 main() {
    if (!BlinkIDSDK.isBrowserSupported()) {
        return;
    }
    const loadSettings = new BlinkIDSDK.WasmSDKLoadSettings(this.licenseKey);
    console.log("hello"); // Getting "hello" in console
     loadSettings.loadProgressCallback = null;
    loadSettings.engineLocation = "https://unpkg.com/@microblink/blinkid-in-browser-sdk/resources/";
    loadSettings.useWebWorker = true;
    loadSettings.workerLocation = "../../../node_modules/@microblink/blinkid-in-browser-sdk/resources";

    BlinkIDSDK.loadWasmModule(loadSettings).then(
        (sdk) => {
          console.log(sdk);
        },
        (error) => {
            console.error("Failed to load SDK!", error);
        }
    );
}

Can you please help me to fix the issue.

**Comment by vjekoart** [comment]
Hello @pjain8889,

The problem is that worker file is not available on the path you have defined in the source code.

I'm assuming you're using `ng serve` during development. In that case, browser cannot access location `../../../node_modules/...`.

You have to manually copy files from `node_modules/@microblink/blinkid-in-browser-sdk/resources/` to location which is accessible from web browser.

For example, in standard Angular application you need to copy folder `node_modules/@microblink/blinkid-in-browser-sdk/resources/` to `src/assets/` directory, where other static assets are placed. In that case, you can use something like `loadSettings.workerLocation = "/assets/resources";` in your Angular application to access the worker file.

Hope this helps,
Vjekoslav
